import {Roboto} from "next/font/google"
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const myfont = Roboto({
  subsets :["latin"],
  weight:["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className = {myfont.className}>
        {children}
      </body>
    </html>
  );
}
